---
- name: restart kubernetes API server
  become: true
  become_user: root
  service: name=kube-apiserver state=restarted

- name: restart kubernetes controller manager
  become: true
  become_user: root
  service: name=kube-controller-manager state=restarted

- name: restart kubernetes scheduler
  become: true
  become_user: root
  service: name=kube-scheduler state=restarted
