---
# Creates the image that the VMs will boot from.

- name: create tmp directory
  file: path=./tmp state=directory mode=0755

- name: download Atomic image
  get_url: dest=./tmp/atomic.qcow2 timeout=3600 url={{ atomic_image_url }}

- name: register Atomic image
  os_image:
    name: "{{ image_name }}"
    container_format: bare
    disk_format: qcow2
    timeout: 3600
    filename: ./tmp/atomic.qcow2
    cloud: "{{ os_cloud }}"

