---
# Docker set up to use a flannel overlay network.
# Heavily inspired from: http://www.projectatomic.io/docs/gettingstarted/

- name: write flannel config
  become: true
  become_user: root
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
  - restart flannel
  - restart docker daemon

- name: enable and start flannel
  become: true
  become_user: root
  service: name=flanneld enabled=yes state=started

- name:  create docker systemd drop-in directory
  become: true
  become_user: root
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: write docker systemd drop-in for flannel
  become: true
  become_user: root
  template:
    src: docker_flanneld_network.j2
    dest: /etc/systemd/system/docker.service.d/10-flanneld-network.conf
  register: systemd_unit
  notify:
  - restart docker daemon

- name: reload systemd configuration
  command: systemctl daemon-reload
  become: true
  become_user: root
  when: systemd_unit.changed == True
