---
# Kubernetes worker.
# Heavily inspired from: http://www.projectatomic.io/docs/gettingstarted/

- name: enable and start kubelet
  become: true
  become_user: root
  service: name=kubelet enabled=yes state=started

- name: enable and start kube-proxy
  become: true
  become_user: root
  service: name=kubelet enabled=yes state=started
