---
- name: reboot atomic server
  become: true
  become_user: root
  command: systemctl reboot
  ignore_errors: true

- name: wait for atomic server to come back up
  local_action: >
    wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }}
    search_regex=OpenSSH delay=2
  become: false

- name: reload facts after atomic upgrade
  setup:

