---
- name: restart kubelet
  become: true
  become_user: root
  service: name=kubelet state=restarted

- name: restart kube-proxy
  become: true
  become_user: root
  service: name=kube-proxy state=restarted
