---
# Kubernetes master.
# Heavily inspired from: http://www.projectatomic.io/docs/gettingstarted/

- name: compute internal network IP
  set_fact:
    internal_net_ip: >
        {{ ansible_all_ipv4_addresses | ipaddr(internal_net_cidr) | first }}

- name: write kubernetes config
  become: true
  become_user: root
  template: src=k8s_config.j2 dest=/etc/kubernetes/config
  notify:
  - restart kubernetes API server
  - restart kubernetes controller manager
  - restart kubernetes scheduler

- name: write kubernetes API config
  become: true
  become_user: root
  template: src=k8s_apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
  - restart kubernetes API server

- name: write kubernetes controller manager config
  become: true
  become_user: root
  template:
    src: k8s_controller_manager.j2
    dest: /etc/kubernetes/controller-manager
  notify:
  - restart kubernetes controller manager

- name: enable and start kubernetes API server
  become: true
  become_user: root
  service: name=kube-apiserver enabled=yes state=started

- name: enable and start kubernetes controller manager
  become: true
  become_user: root
  service: name=kube-controller-manager enabled=yes state=started

- name: enable and start kubernetes scheduler
  become: true
  become_user: root
  service: name=kube-scheduler enabled=yes state=started
